:stylesheet: style.css
:doctype: book

= Lubuntu Setup

== Launcher


The simplest is to use `ALT-F2`, then type name of the application.
Alternatively, you can install _Gnome-Do_

1. `sudo apt-get install gnome-do`
2. Configure gnome-do to start with the OS
3. Make sure the superkey + space is the hotkey

== Terminals

1. `sudo apt-get install guake terminator`
2. `sudo apt-get install terminator`
3. remap the keybindings
4. configure as login shell

== Java

To install the oracle JVM and JDK, add webupd8team repository and pull
the specific JDK version from the repo

----
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo update-alternatives --config java
----

If you need JDK 7;

`sudo apt-get install oracle-java7-installer`

then switch your JDK using 

`sudo update-alternatives --config java`


== Ruby

Install the Ruby Version Manager (rvm), then install your specific
version of ruby

----
curl -sSL https://get.rvm.io | bash
rvm install 2.1.3
rvm create alias 2.1.3 # make this version the default
gem install asciidoctor # for writing
gem install jekyll # for static website
gem install pygments.rb
----


== Python

.The most basic way to install Python
====
....
sudo apt-get install python-setuptools
sudo easy_install pip
sudo pip pygments 
....
====

Using the new Python notebooks requires a bit more software, there are
many out there but we will use Jupyter, this is a popular software
among Python enthusiast.

1. Go to the Continuum website at
   https://www.continuum.io/downloads[https://www.continuum.io/downloads]
2. Download the Anaconda installer. At this point, you most likely
   have the Python 2.x version, so choose that for the download
3. Follow the instruction on the website on how to install Anaconda,
   most likely, it simply be a bash command
+
----
bash Anaconda2-4.2.0-Linux-x86_64.sh 
----
4. Install the Jupyter software using the command `conda install
   jupyter`
   
To start using the interactive notebook, create a working directory
and start the notebook from there

.Starting a Python notebook
====
....
mkdir pythontest && cd pythontest
jupyter notebook
....
====

It will start a webserver and quite possibly, launch your default
browser as well. Then you can start mucking around the notebook


== NodeJS

Install NVM first.

....
curl -o-
https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh |
bash
....

Then install a version of node

....
nvm install 6.3.1
....

Start getting some software via *npm*

....
npm install -g nodemon
npm install -g http-server
....

Perhaps, get another version of node

....
nvm install 6.2.2
....

== Editors and Tmux


Get vim, tmux, emacs and git

....
sudo apt-get install vim-nox tmux emacs git
....

Pull your configs and put them on a work area folder

....
mkdir workarea && cd workarea 
git clone https://github.com/tedhagos/configs.git
....

I saved my vimrc, tmux.conf, bashrc and other stuff on a git repo,
that's why I pulled the configs.git.

Get the vimrc sorted out.
....
cd ~ && cp ~/workarea/vimrc .vimrc
....

Then get the tmux.conf sorted out
....
cp ~/workarea/tmux.conf .tmux.conf
....

Get some nice fonts for the terminal
....
sudo apt-get install fonts-inconsolata
....

And configure terminals to use _inconsolata_

== Music

1. Replace the default sound server
2. `sudo add-apt-repository ppa:nilarimogard/webupd8`
3. `sudo apt-get update`
4. `sudo apt-get install pulseaudio-equalizer`
5. Change the settings of the equalizer, search "equalizer" in
   gnome-do
6. `sudo apt-get install cmus`

// CLOUD STORAGE
include::chapters/cloud-storage.adoc[]


== HP Printers

1. `sudo apt-get install hplip hplip-gui`
2. Use the HPLip toolbox to setup the printers
3. Launch gnome-do, search "HPLip toolbox"


== nvPY

nvPY is a note-taking application. It's a python-based equivalent of
Notational Velocity (OSX). It was used by a lot of people to sync with
SimpleNote, but it can be configured to read from a Dropbox directory
(or any directory for that matter).

....
sudo apt-get install nvpy
....

Create a config file for nvpy

....
touch ~/.nvpy.cfg
....

Create the nvpy configuration file on your home folder

.nvpy.cfg
....
[nvpy]
notes_as_txt = 1
txt_path = /home/thagos/Dropbox/notes

#disable simplenote syncing, use 1 to enable it
simplenote_sync = 0

# 0 value will sort in alphanumeric mode
sort_mode = 1
....

== Ripping tools

*Youtube*

----
sudo apt-get install youtube-dl
youtube-dl <youtue URL>
----

*Download accelerator*

----
sudo apt-get install axel
axel -n 10 <URL>
----

== Writing toolchain

----
rvm use 2.1.3 # or any other ruby version you are using
gem install asciidoctor
----

*DocBook*

----
sudo apt-get install xsltproc docbook-xsl-ns docbook5-xml
----

// Package Management
include::chapters/package-manager.adoc[]


// Email
include::chapters/email.adoc[]







